/**
 * synthPresets — Built-in synthesizer preset patches for WebAudioSynth.
 *
 * Pure preset data, extracted from WebAudioSynth.js so that module can stay
 * focused on synthesis logic. PRESETS is consumed across the app and is also
 * re-exported from WebAudioSynth.js for backward compatibility.
 */

export const PRESETS = {
  // --- Retro / Chiptune ---
  chip_lead: {
    name: 'Chip Lead',
    family: 'chip',
    oscillator: { type: 'square', detune: 0 },
    envelope: { attack: 0.005, decay: 0.1, sustain: 0.8, release: 0.1 },
    filter: { type: 'lowpass', frequency: 12000, Q: 0.5 },
    gain: 0.35,
  },
  chip_bass: {
    name: 'Chip Bass',
    family: 'chip',
    oscillator: { type: 'square', detune: 0 },
    envelope: { attack: 0.005, decay: 0.2, sustain: 0.5, release: 0.15 },
    filter: { type: 'lowpass', frequency: 2000, Q: 2 },
    gain: 0.45,
  },
  cyber_secks: {
    name: 'Cyber Secks',
    family: 'chip',
    oscillator: { type: 'sine', detune: 0 },
    oscillator2: { type: 'sine', detune: 1200, gain: 0.72 },
    envelope: { attack: 0.008, decay: 0.08, sustain: 0.85, release: 0.08 },
    filter: { type: 'bandpass', frequency: 900, Q: 7 },
    gain: 0.32,
    drive: 0.18,
  },
  heartbound: {
    name: 'Heartbound',
    family: 'chip',
    oscillator: { type: 'square', detune: 0 },
    oscillator2: { type: 'triangle', detune: 1200, gain: 0.3 },
    envelope: { attack: 0.004, decay: 0.12, sustain: 0.65, release: 0.16 },
    filter: { type: 'lowpass', frequency: 7200, Q: 0.8 },
    gain: 0.34,
    drive: 0.04,
  },
  triforce: {
    name: 'Triforce',
    family: 'chip',
    oscillator: { type: 'triangle', detune: 0 },
    envelope: { attack: 0.003, decay: 0.1, sustain: 0.78, release: 0.1 },
    filter: { type: 'lowpass', frequency: 9500, Q: 0.4 },
    gain: 0.42,
    drive: 0,
  },
  bliff: {
    name: 'Bliff',
    family: 'chip',
    oscillator: { type: 'sawtooth', detune: -7 },
    oscillator2: { type: 'square', detune: -1200, gain: 0.28 },
    envelope: { attack: 0.004, decay: 0.18, sustain: 0.5, release: 0.12 },
    filter: { type: 'lowpass', frequency: 850, Q: 6 },
    gain: 0.52,
    drive: 0.48,
  },

  // --- Modern / Ambient ---
  soft_pad: {
    name: 'Soft Pad',
    family: 'modern',
    schemaVersion: 2,
    oscillator: { type: 'sine', detune: 4 },
    oscillator2: { type: 'triangle', detune: 1200, gain: 0.16 },
    envelope: { attack: 0.075, decay: 0.56, sustain: 0.72, release: 1.25 },
    filter: { type: 'lowpass', frequency: 2800, Q: 0.72 },
    filterEnv: { attack: 0.05, decay: 0.9, sustain: 0.62, depth: 0.28 },
    vibrato: { rate: 4.1, depth: 4, delay: 0.45 },
    unison: { voices: 3, spread: 10 },
    keyTrack: 0.24,
    velocityResponse: { filter: 0.34, drive: 0.015 },
    stereoWidth: 0.34,
    gain: 0.34,
    drive: 0.012,
  },
  shimmer_lead: {
    name: 'Shimmer Lead',
    family: 'modern',
    schemaVersion: 2,
    oscillator: { type: 'sawtooth', detune: 2 },
    oscillator2: { type: 'sine', detune: 1200, gain: 0.14 },
    envelope: { attack: 0.022, decay: 0.28, sustain: 0.44, release: 0.72 },
    filter: { type: 'lowpass', frequency: 5200, Q: 2.6 },
    filterEnv: { attack: 0.01, decay: 0.34, sustain: 0.26, depth: 0.34 },
    vibrato: { rate: 5.4, depth: 5, delay: 0.16 },
    unison: { voices: 3, spread: 8 },
    keyTrack: 0.3,
    velocityResponse: { filter: 0.42, drive: 0.03 },
    stereoWidth: 0.28,
    gain: 0.28,
    drive: 0.04,
  },

  // --- Lo-fi ---
  lofi_keys: {
    name: 'Lo-fi Keys',
    family: 'modern',
    schemaVersion: 2,
    oscillator: { type: 'triangle', detune: 7 },
    oscillator2: { type: 'sine', detune: 1200, gain: 0.16 },
    envelope: { attack: 0.018, decay: 0.38, sustain: 0.34, release: 0.62 },
    filter: { type: 'lowpass', frequency: 2450, Q: 1.35 },
    filterEnv: { attack: 0.01, decay: 0.42, sustain: 0.24, depth: 0.26 },
    vibrato: { rate: 3.6, depth: 5, delay: 0.12 },
    unison: { voices: 2, spread: 6 },
    keyTrack: 0.22,
    velocityResponse: { filter: 0.36, drive: 0.035 },
    stereoWidth: 0.26,
    gain: 0.34,
    drive: 0.08,
  },
  warm_bass: {
    name: 'Warm Bass',
    family: 'modern',
    schemaVersion: 2,
    oscillator: { type: 'sawtooth', detune: 0 },
    oscillator2: { type: 'square', detune: -1200, gain: 0.16 },
    envelope: { attack: 0.006, decay: 0.28, sustain: 0.44, release: 0.22 },
    filter: { type: 'lowpass', frequency: 1120, Q: 4.2 },
    filterEnv: { attack: 0.003, decay: 0.24, sustain: 0.2, depth: 0.46 },
    unison: { voices: 2, spread: 4 },
    keyTrack: 0.15,
    velocityResponse: { filter: 0.32, drive: 0.06 },
    stereoWidth: 0.16,
    gain: 0.46,
    drive: 0.18,
  },

  // --- Classic ---
  pluck: {
    name: 'Pluck',
    family: 'chip',
    oscillator: { type: 'triangle', detune: 0 },
    envelope: { attack: 0.003, decay: 0.25, sustain: 0.0, release: 0.3 },
    filter: { type: 'lowpass', frequency: 6000, Q: 1 },
    gain: 0.5,
  },
  organ: {
    name: 'Organ',
    family: 'modern',
    schemaVersion: 2,
    oscillator: { type: 'sine', detune: 0 },
    oscillator2: { type: 'sine', detune: 1200, gain: 0.34 },
    envelope: { attack: 0.006, decay: 0.06, sustain: 0.88, release: 0.08 },
    filter: { type: 'lowpass', frequency: 8200, Q: 0.55 },
    filterEnv: { attack: 0.004, decay: 0.18, sustain: 0.7, depth: 0.12 },
    vibrato: { rate: 5.8, depth: 3, delay: 0.22 },
    unison: { voices: 2, spread: 3 },
    keyTrack: 0.08,
    velocityResponse: { filter: 0.22, drive: 0.015 },
    stereoWidth: 0.18,
    gain: 0.34,
    drive: 0.025,
  },
  modern_keys: {
    name: 'Modern Keys',
    family: 'modern',
    schemaVersion: 2,
    oscillator: { type: 'triangle', detune: 0 },
    oscillator2: { type: 'sine', detune: 1200, gain: 0.18 },
    envelope: { attack: 0.018, decay: 0.38, sustain: 0.38, release: 0.72 },
    filter: { type: 'lowpass', frequency: 3100, Q: 1.1 },
    filterEnv: { attack: 0.012, decay: 0.45, sustain: 0.28, depth: 0.42 },
    vibrato: { rate: 4.8, depth: 5, delay: 0.18 },
    unison: { voices: 3, spread: 9 },
    keyTrack: 0.25,
    velocityResponse: { filter: 0.44, drive: 0.025 },
    stereoWidth: 0.3,
    gain: 0.34,
    drive: 0.035,
  },
  modern_pad: {
    name: 'Modern Pad',
    family: 'modern',
    schemaVersion: 2,
    oscillator: { type: 'sawtooth', detune: -3 },
    oscillator2: { type: 'triangle', detune: 1200, gain: 0.22 },
    envelope: { attack: 0.09, decay: 0.8, sustain: 0.74, release: 1.6 },
    filter: { type: 'lowpass', frequency: 2200, Q: 0.8 },
    filterEnv: { attack: 0.07, decay: 1.15, sustain: 0.62, depth: 0.56 },
    vibrato: { rate: 4.2, depth: 7, delay: 0.35 },
    unison: { voices: 3, spread: 14 },
    keyTrack: 0.36,
    velocityResponse: { filter: 0.3, drive: 0.012 },
    stereoWidth: 0.42,
    gain: 0.28,
    drive: 0.015,
  },
  modern_bass: {
    name: 'Modern Bass',
    family: 'modern',
    schemaVersion: 2,
    oscillator: { type: 'sawtooth', detune: 0 },
    oscillator2: { type: 'square', detune: -1200, gain: 0.2 },
    envelope: { attack: 0.006, decay: 0.22, sustain: 0.48, release: 0.18 },
    filter: { type: 'lowpass', frequency: 950, Q: 5 },
    filterEnv: { attack: 0.004, decay: 0.26, sustain: 0.18, depth: 0.68 },
    vibrato: null,
    unison: { voices: 2, spread: 5 },
    keyTrack: 0.18,
    velocityResponse: { filter: 0.34, drive: 0.06 },
    stereoWidth: 0.18,
    gain: 0.46,
    drive: 0.22,
  },
  modern_pluck: {
    name: 'Modern Pluck',
    family: 'modern',
    schemaVersion: 2,
    oscillator: { type: 'triangle', detune: 0 },
    oscillator2: { type: 'sawtooth', detune: 1200, gain: 0.12 },
    envelope: { attack: 0.004, decay: 0.24, sustain: 0.05, release: 0.52 },
    filter: { type: 'lowpass', frequency: 4200, Q: 1.6 },
    filterEnv: { attack: 0.002, decay: 0.22, sustain: 0.05, depth: 0.74 },
    vibrato: { rate: 5.2, depth: 4, delay: 0.2 },
    unison: { voices: 3, spread: 7 },
    keyTrack: 0.42,
    velocityResponse: { filter: 0.48, drive: 0.02 },
    stereoWidth: 0.24,
    gain: 0.36,
    drive: 0.02,
  },
  // --- FM (2-operator) ---
  // `fm.ratio` = modulator:carrier frequency ratio (integer = harmonic/clean,
  // non-integer = inharmonic/metallic). `fm.index` = modulation depth; it decays
  // from `index` toward `index*indexSustain` over `fm.decay` seconds, which is
  // what makes the attack bright and the body mellow.
  fm_epiano: {
    name: 'FM E-Piano',
    family: 'fm',
    type: 'fm',
    oscillator: { type: 'sine', detune: 0 },
    fm: { ratio: 1, index: 2.6, indexSustain: 0.12, decay: 0.22 },
    envelope: { attack: 0.002, decay: 1.4, sustain: 0.28, release: 0.45 },
    filter: { type: 'lowpass', frequency: 9000, Q: 0.5 },
    keyTrack: 0.12,
    velocityResponse: { filter: 0.3, drive: 0 },
    gain: 0.5,
    drive: 0.02,
  },
  fm_bell: {
    name: 'FM Bell',
    family: 'fm',
    type: 'fm',
    oscillator: { type: 'sine', detune: 0 },
    fm: { ratio: 1.41, index: 4.2, indexSustain: 0.4, decay: 1.1 },
    envelope: { attack: 0.001, decay: 2.4, sustain: 0.0, release: 1.4 },
    filter: { type: 'lowpass', frequency: 11000, Q: 0.4 },
    gain: 0.42,
  },
  fm_glass_bass: {
    name: 'FM Glass Bass',
    family: 'fm',
    type: 'fm',
    oscillator: { type: 'sine', detune: 0 },
    fm: { ratio: 0.5, index: 1.6, indexSustain: 0.18, decay: 0.16 },
    envelope: { attack: 0.004, decay: 0.3, sustain: 0.55, release: 0.18 },
    filter: { type: 'lowpass', frequency: 2600, Q: 1.4 },
    keyTrack: 0.2,
    velocityResponse: { filter: 0.34, drive: 0.04 },
    gain: 0.5,
    drive: 0.06,
  },
  fm_mallet: {
    name: 'FM Mallet',
    family: 'fm',
    type: 'fm',
    oscillator: { type: 'sine', detune: 0 },
    fm: { ratio: 3.5, index: 3.2, indexSustain: 0.0, decay: 0.07 },
    envelope: { attack: 0.001, decay: 0.5, sustain: 0.0, release: 0.22 },
    filter: { type: 'lowpass', frequency: 10000, Q: 0.5 },
    gain: 0.46,
  },
};
